#!/usr/bin/tclsh
puts "Enter the operation to be performed:"
gets stdin optr

puts "Enter number 1:"
gets stdin num1

puts "Enter number 2:"
gets stdin num2

switch $optr {
    "+" {
        puts "result = [expr $num1 + $num2]"
    }
    "-" {
        puts "result = [expr $num1 - $num2]"
    }
    "*" {
        puts "result = [expr $num1 * $num2]"
    }
    "/" {
        puts "result = [expr $num1 / $num2]"
        }
}
